
POST {{baseUrl}}/token
Authorization: Basic {{authorization}}

###

GET {{baseUrl}}/cases
Accept: application/json
Authorization: Bearer {{access_token}}

###

GET {{baseUrl}}/casesSuspected
Accept: application/json
Authorization: Bearer {{access_token}}

###

GET {{baseUrl}}/casesConfirmed
Accept: application/json
Authorization: Bearer {{access_token}}

###

GET {{baseUrl}}/deaths
Accept: application/json
Authorization: Bearer {{access_token}}

###

GET {{baseUrl}}/recovered
Accept: application/json
Authorization: Bearer {{access_token}}